#!/usr/bin/env bash

bericht="$1"

while read -r file; do
	if [[ "$file" =~ py$ ]]; then
		bericht=$(python3 "$file" "$bericht")
	elif [[ "$file" =~ js$ ]]; then
		bericht=$(node "$file" "$bericht")
	elif [[ "$file" =~ md$ ]]; then
		:
	else
		echo "onbekend script"
	fi

done < <(find src -type f | sort)

echo "$bericht"
